version: "3.8"

services:
  app:
    build:
      context: ..
      target: devel
      dockerfile: ../Dockerfile
    container_name: {{ cookiecutter.system }}-dev-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-myapp_dev}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-myapp_dev}
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - {{ cookiecutter.system }}python-cache:/home/vscode/.cache
    ports:
      - "8000:8000"
      - "5000:5000"
    working_dir: /app
    command: sleep infinity

  db:
    image: postgres:17
    container_name: {{ cookiecutter.system }}-dev-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-myapp_dev}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - {{ cookiecutter.system }}-postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-myapp_dev}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: {{ cookiecutter.system }}-dev-cache
    ports:
      - "6379:6379"
    volumes:
      - {{ cookiecutter.system }}-redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  {{ cookiecutter.system }}-postgres_data:
    driver: local
  {{ cookiecutter.system }}-redis_data:
    driver: local
  {{ cookiecutter.system }}-python-cache:
    driver: local
